src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/Native.cs
src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/UWPApplication.cs

fixing the indirect string loader to not pass in null

Fixing string loader

---

src/modules/cmdpal/Exts/EverythingExtension/EverythingExtensionCommandsProvider.cs
src/modules/cmdpal/Exts/EverythingExtension/Pages/EverythingExtensionPage.cs
src/modules/cmdpal/Exts/HackerNewsExtension/HackerNewsCommandsProvider.cs
src/modules/cmdpal/Exts/HackerNewsExtension/Properties/launchSettings.json
src/modules/cmdpal/Exts/MastodonExtension/MastodonExtensionPage.cs
src/modules/cmdpal/Exts/MediaControlsExtension/MediaActionsProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarksCommandProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorCommandProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.CmdPalSettings/SettingsCommandProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Registry/RegistryCommandsProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/WindowsServicesCommandsProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsSettings/WindowsSettingsCommandsProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsTerminal/WindowsTerminalCommandsProvider.cs
src/modules/cmdpal/Exts/ProcessMonitorExtension/ProcessMonitorCommandProvider.cs
src/modules/cmdpal/Exts/SSHKeychainExtension/SSHKeychainCommandsProvider.cs
src/modules/cmdpal/Exts/SamplePagesExtension/SamplePagesCommandsProvider.cs
src/modules/cmdpal/Exts/SpongebotExtension/SpongebotCommandsProvider.cs
src/modules/cmdpal/Exts/TemplateExtension/TemplateExtensionCommandsProvider.cs
src/modules/cmdpal/Exts/YouTubeExtension/YouTubeExtensionCommandsProvider.cs
src/modules/cmdpal/WindowsCommandPalette/Builtins/QuitAction/QuitCommandProvider.cs
src/modules/cmdpal/WindowsCommandPalette/Builtins/ReloadExtensionsCommandProvider.cs
src/modules/cmdpal/WindowsCommandPalette/CommandPaletteHost.cs
src/modules/cmdpal/WindowsCommandPalette/MainWindow.xaml.cs
src/modules/cmdpal/WindowsCommandPalette/Views/CommandProviderWrapper.cs
src/modules/cmdpal/doc/command-pal-anatomy/command-palette-anatomy.md
src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/CommandProvider.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ExtensionHost.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ProgressState.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl

Allow extensions to send status messages to the host app.
As an example, you can now:
```cs
ExtensionHost.LogMessage(new LogMessage() { Message = "This is a test, from the HackerNews sample" });
```
And have that appear in the host apps debug console. 
Closes #134 
Closes #118 
Should also make resolving #87 and #135 easier. 
We don't have the design of these status messages totally planned out yet. But this should at least make it possible. For those in the back, **this does not actually display these messages anywhere in the host UX currently**. 
-----
Other information that's currently included:
* The host app's HWND. Way too many times does the Windows API need an HWND, which extensions won't have, but the host app does. 
* The `LanguageOverride`. This is in case we ever want to …

Create an `IExtensionHost` class, to enable logging

---

src/modules/cmdpal/Exts/EverythingExtension/EverythingExtension.csproj
src/modules/cmdpal/Exts/HackerNewsExtension/HackerNewsExtension.csproj
src/modules/cmdpal/Exts/MastodonExtension/MastodonExtension.csproj
src/modules/cmdpal/Exts/MediaControlsExtension/MediaControlsExtension.csproj
src/modules/cmdpal/Exts/ProcessMonitorExtension/ProcessMonitorExtension.csproj
src/modules/cmdpal/Exts/SSHKeychainExtension/SSHKeychainExtension.csproj
src/modules/cmdpal/Exts/SamplePagesExtension/SamplePagesExtension.csproj
src/modules/cmdpal/Exts/SpongebotExtension/SpongebotExtension.csproj
src/modules/cmdpal/Exts/TemplateExtension/TemplateExtension.csproj
src/modules/cmdpal/Exts/YouTubeExtension/YouTubeExtension.csproj

Whoops. 
We were accidentally deploying all the extension packages to the _same_ directory. That meant we could only ever register one at a time - including the extension host. yikes.

Fix the build

---

src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs

Does the `ExtendsContentIntoTitleBar` thing to hide the titlebar.
Also re-adds the logic that resizes our drag rect, so that the window is movable again.

Hide the titlebar, again

---

Directory.Packages.props
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandProviders/QuitAction.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandProviders/QuitCommandProvider.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandProviders/ReloadExtensionsAction.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandProviders/ReloadExtensionsCommandProvider.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/QuitMessage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Microsoft.CmdPal.UI.ViewModels.csproj
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ActionBarContextItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ActionBarViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ListViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ShellViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml.cs

- 17a3088ea581ec0826ffa212103fe3099d085c32 Switches non-AOT safe RegisterAll call to Register with type for Messenger pattern
- fa962a574db0bcf168f322127bc3fbae8c649e7a Use Dependency Injection for Constructor of ShellViewModel to start this pattern going (as we covered in the MVVM crash course mtg)
- 0bdd21a837352bba13901a7fc58ff28f89551147 Re-add Quit/Reload and use Messenger, but they won't appear in UI yet as Fallback Commands and we don't have search
- dd1b1289cb4ccf4a1dece59f5ed4bb206c5ee39a Setup initial debounce strategy for search in UI layer, though search still not implemented (think found a WCT bug too, will investigate)
- 98041ea11043732fa449c7a99d9e64d43597fcaf Update to latest WCT packages to help us test before our release 😅

Some various minor clean-up

---

src/modules/cmdpal/check-extensions.ps1
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/Microsoft.CmdPal.Extensions.Helpers.csproj

1. Manually copy `Microsoft.CmdPal.Extensions.winmd` into our helper library's output directory. If we do that, then it rolls up to the packages that reference it. 
* This only started failing for me on 17.13. Before that (I think on 17.11) this just worked automatically?
* This feels bodgy
2. Update the helper script to be more informative
Refs #104. I don't want to say that it fixes it till we never see it again, but I think this fixes it.
I did not test this on 17.11. I'll need to find a machine that has it to make sure I don't explode the world

I think this fixes our winmd pains, but at what cost

---

src/modules/cmdpal/Microsoft.CmdPal.UI/Properties/launchSettings.json

I got the extensions loading in TRA, but literally every WinRT call I made resulted in spew like:
```
Exception thrown at 0x00007FFE9422FA4C (KernelBase.dll) in Microsoft.CmdPal.UI.exe: WinRT originate error - 0x80040155 : 'Failed to find proxy registration for IID: {377D30E5-0D97-577F-A0F1-2E916A03B4E1}.'.
'Microsoft.CmdPal.UI.exe' (Win32): Loaded 'D:\dev\public\powertoys\x64\Debug\WinUI3Apps\CmdPal\AppX\Microsoft.CmdPal.Extensions.winmd'. Module was built without symbols.
Exception thrown at 0x00007FFE9422FA4C (KernelBase.dll) in Microsoft.CmdPal.UI.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040155, 0x0000000080004002, 0x000000000000001D, 0x000000341FA7E750).
```
(Some `RoOriginate`s and WinRT transform exceptions). NOTABLY, these got logged to VS's debug output, …

Silence nativeDebugging spew

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsCommandProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsPage.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/OpenPathAction.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs

Pretty straightforward. This never got ported, because it didn't have a CommandProvider. Now it does.

Add the All Apps page to the MVVM app.

---

Directory.Packages.props
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsTerminal/Microsoft.CmdPal.Ext.WindowsTerminal.csproj
src/modules/cmdpal/Microsoft.Terminal.UI/Microsoft.Terminal.UI.vcxproj
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/Microsoft.CmdPal.Extensions.Helpers.csproj
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.vcxproj

Supersedes #200
I also had to:
* Manually restore the WebView2 package into `/packages`. I'm assuming this was just VS being dumb and most people won't have to?
* `git clean -fdx -e *.user -e *.cmd -e packages/** -e Appx/** -e *.svg`  
* I did it this way because MAYBE i had a couple WIP extensions that I didn't want to nuke, and one .svg file in particular that I yanked from espn.com that I didn't want to nuke

Bump our WebView2 version, to fix a bunch of build breaks

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TagViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml

Doesn't use all these everywhere, but starts plumbing them into ViewModel's so that @niels9001 can start using more things in more places. 
I didn't actually colorize the tags, because that requires a Brush, and I don't think I'm supposed to put brushes in the viewmodels
ref #73

Add a bunch more ListItem viewmodel properties, namely tags

---

src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/packages.config

from https://github.com/zadjii-msft/PowerToys/pull/205
There's another NuGet config file we have for cmdpal in `src\modules\cmdpal\extensionsdk\Microsoft.CmdPal.Extensions\packages.config` that also needed its version updated, then VS will properly restore the right version on build, this I assume is masking any versions defined in the root `Directory.Packages.props` file changed in 205. 
The comment about needing to do a manual restore was correct. VS was looking at this config and only downloading the old version to the packages folder and not grabbing the new one. Thus anyone pulled fresh, didn't have the new version and VS wouldn't find the target file being looked for in the vcxproj file and provide the error message:
```
2>------ Build started: Project: Version, Configuration: Debug …
```

Fix missed config update to WebView2 version

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Commands/SwitchToWindowCommand.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Components/SearchController.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Helpers/SettingsManager.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Pages/WindowWalkerListPage.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Properties/Resources.Designer.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Properties/Resources.resx
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/WindowWalkerCommandsProvider.cs

* Add the app's icon, if we can
* Add a setting to display the results in-order (THE NEW DEFAULT)
* Change a couple strings to be tighter, less "power-user"-sounding
* Let the code formatter do its buisiness
Originally from 0b789ad, on `dev/migrie/f/stash-forms-should-submit`, which was buried like 7 branches deep.

Minor Window Walker improvements

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandProviderWrapper.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/QuitCommandProvider.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandManager.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandWrapper.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ListHelpers.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Shell/FallbackExecuteItem.cs

Add support for fallback commands again. Couple important parts:
* Lists shouldn't contain items with blank `Title`s. That's spec'd that way, and allows fallback items to hide themselves if they don't want to be shown for a given search string
* The CommandProviderWrapper, as well as extension infrastructure needs to know to get the fallbacks out of a commandprovider too. 
* `TopLevelCommandWrapper` needs to know when its model changes, to update itself in the list

Make fallback commands work again

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandWrapper.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ListHelpers.cs

As it stands, since the shell/run handler always exactly matches the `SearchText`, it _always_ shows up first in the results. 
That's annoying. Make it a little less popular. Sometimes, you just have to be mean to the kid that's really, really popular.

Down-weight fallback handlers

---

src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ListHelpers.cs

I think this is what @joadoumie  was seeing when he thought the main page crashed a lot. 
Some weird bug where the main page gcrashes with some frequency if the first thing you type is a space. Weird. `FuzzySearch` just can't handle the space

Don't kill the mainpage when typing a space

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs

Random nits, part the third
Whoops. Looks like the context menu was pretty specifically _not_ getting initialized with the default command. It definitely should.

Actually add all the commands to the context menu

---

src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ActionBar.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml

Yea, this one's stupid. I spent too long debugging why changing the list of tags in an extension didn't do anything. Turns out, we just never had XAML listen for the PropertyChanged. That hurts.

Tags should be Mode=OneWay in the XAML

---

src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml.cs

I think I added this to the spec while there was like, 80 branches flying around and never actually merged support for it in the host app. Oops.

Support CommandResult.GoBack in the host

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/AddBookmarkForm.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarkPlaceholderForm.cs
src/modules/cmdpal/Exts/SpongebotExtension/SpongeSettingsForm.cs
src/modules/cmdpal/Exts/YouTubeExtension/Pages/YouTubeAPIForm.cs

Random nits, part the second
TRA is particular about form pages. It'll actually break itself if an extension throws an exception (which it should do). The POC was more forgiving (but technically incorrect)
Well, turns out, all the form pages we had did not give an F and just threw exceptions. They shouldn't! That's bad!

Fix all the broken form pages

---

src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs

PowerToys Run has 50ms as the default input smoothing: 
This PR simply changes the current value from 100ms to 50ms. This causes a noticeable improvement for fast typers.

Change the default debounce timer from 100ms to 50ms

---

src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs

This PR adjusts the UX for single-clicking / double-clicking on list items. With this change: 
- A single-click on a list item will navigate the user to that list item. It will not automatically invoke the associated command.
- A double-click on a list item will invoke the command for the list item.
It is a really small code change, _but_ I have a suspicion that there are cleaner ways to handle what I'm doing. Since it is so small, I figured just creating the PR and getting quick @zadjii-msft feedback would do the trick.

Change single/double click behavior on list items

---

src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/KeyVisual/KeyVisual.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/KeyVisual/KeyVisual.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutControl.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutControl.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutDialogContentControl.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutDialogContentControl.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutWithTextLabelControl.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutWithTextLabelControl.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsPage.xaml

When I pilfered the ShortcutControl, I didn't change the namespaces at all. I also didn't build the whole PT sln.
After the latest merge with upstream, either I built more or new rules got added, and now there are conflicts, since the same exact type is being built in two places.
Easy enough to fix that

Fix the namespaces for the pilfered KB control

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandWrapper.cs

Right now, the main page really explodes if an extension dies. It really does not like it. 
Instead, this PR changes it so that if we fail to load the properties from an ICommandItem, we won't kill the whole page, we'll just replace that _single_ item with an error item. This looks like:
(which will look better after #265)

When an extension item fails to load, replace it with an error item

---

src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/GoToPageArgs.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl

As discussed in #273.
This will allow extensions that want to navigate around the page stack more control.
For example, the Obsidian Notes extension will want to start with a form for "Set up vault path". When they submit, instead of just going home, they'll want to GoToPage('com.obsidian.notes', mode=GoHome), so that submitting the form takes them to the notes list, rather than just _home_.
Doesn't actually implement this, of course. Just gets the API ready for it.

Spec `GoToPageArgs.NavigationMode`

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/AliasManager.cs

The alias was only ever added into the proof-of-concept project, which nobody ever uses anymore, whoops. We're on to bigger and better things of course... TRA!
This PR simply adds `??` as an alias for the web search plugin for self-hosting in TRA.

Add `??` alias to TRA for web search plugin

---

src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs

Hey guess what, 24px is too tall! If you reserve 24 for the titlebar "drag area", it'll steal input from the top half of the back button, making it un-clickable. fun!

Fix clicks not working on the top half of the back button

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandProviderWrapper.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/DetailsViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/IconDataViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/IconInfoViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/PageViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ProviderSettingsViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TagViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/IconBox.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/IconCacheService.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/IconCacheProvider.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml.cs

(targets #308, which targets #299)
`IconData` and `IconInfo` are unfortunately, not trivially marshallable into the host process. This creates a collection of cases where an app can crash and take the host down, because we'll try to inquire something about the icon. 
It broke reloading when an extension crashed. 
It broke backing out of a crashed extension. 
Previously: #218 
Closes #235

Add an Icon ViewModel, to cache data locally

---

src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WebSearch/FallbackExecuteSearchItem.cs

The fallback command was still showing up on empty query because we weren't explicitly setting the underlying command name to the empty string when it is empty. This is what it looked like in the root view: 
This is a really small PR that just fixes that issue.

Fix the Web Search Fallback Command

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/FocusSearchBoxMessage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListDetailPage.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsPage.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml.cs

Is your name Clint? Do you like settings? Did you hate that backspace on the main page could dismiss the palette? If you said yes to any of that, you're in luck! This PR is for you!
This PR adds three new settings:
* `BackspaceGoesBack`: Controls if backspace with an empty search takes you back a level
* `SingleClickActivates`: Allows users to toggle between the "single click selects, double activates" vs "single click activates" behavior
* `HighlightSearchOnActivate`: When `true` (**default**), this will select the text in the search bar when the window is summoned
This drive-by fixes a bug where clicking to select an item stole focus from the search box.
closes #306

Add 3 settings for Clint

---

src/modules/cmdpal/Exts/SamplePagesExtension/Pages/SampleListPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandPaletteHost.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ProgressViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/StatusMessageViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ExtensionHost.cs
src/modules/cmdpal/exts/SamplePagesExtension/Pages/SendMessageCommand.cs

Bits of status messages that were omitted from #281. 
This lets extensions hide messages (and exposes the helper in the helper lib). 
It also adds support for displaying progress as a progress bar underneath the text of the status message. I'll need An Adult to help with the XAML, to re-template the InfoBar to allow a progress wheel in the icon instead, but for now? good enough. 
I'm doing this to unblock the next PR, which should add some rudimentary winget support.

Add support for hiding messages too

---

src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/TextSetting.cs

Add `isMultiline` and `placeholder` to `Input.Text`.
Default is the current behavior: single line without placeholder.

Add isMultiline and placeholder to Input.Text

---

src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs

Title. 
I just noticed that if you move the caret earlier in the input, then type, we'll toss the caret to the end of the input. Ew. Don't do that.
We should only move the caret if the text actually changed from what we already had.

Don't move the caret to the end of the input if nothing changed

---

src/modules/cmdpal/Microsoft.CmdPal.Common/Services/IExtensionService.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandPaletteHost.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Models/ExtensionService.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Models/ExtensionWrapper.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandManager.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/LogMessage.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/WinGetExtensionPage.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/WinGetExtensionCommandsProvider.cs

Closes #370 
The DevHome code was great for "I need something that can lookup extensions and enumerate all of them".
However, the DevHome code is a very blunt hammer when it comes to extensions. The only thing it tracks is "packages changed", and if it gets one of those, it just blows away all the extensions and rebuilds them. Yikes. 
This PR changes `ExtensionService` to be a scalpel. We'll keep `_installedExtensions` fresh. When we get a package install, we'll add only that package's extension to our cache, and let the `TopLevelCommandManager` know. Similarly for updates and uninstalls. 
That way, we can exactly change the top-level list as needed, rather than bluntly forcing all the extensions to reload. 
In the middle of all this, I fixed a bug where uninstalling an extension, then …

Hot (un)load extensions on (un)install

---

src/modules/cmdpal/Exts/EverythingExtension/EverythingExtension.csproj
src/modules/cmdpal/Exts/HackerNewsExtension/HackerNewsExtension.csproj
src/modules/cmdpal/Exts/MastodonExtension/MastodonExtension.csproj
src/modules/cmdpal/Exts/MediaControlsExtension/MediaControlsExtension.csproj
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Microsoft.CmdPal.Ext.WebSearch.csproj
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Pages/WebSearchListPage.cs
src/modules/cmdpal/Exts/PokedexExtension/PokedexExtension.csproj
src/modules/cmdpal/Exts/ProcessMonitorExtension/ProcessMonitorExtension.csproj
src/modules/cmdpal/Exts/SSHKeychainExtension/SSHKeychainExtension.csproj
src/modules/cmdpal/Exts/SamplePagesExtension/SamplePagesExtension.csproj
src/modules/cmdpal/Exts/SpongebotExtension/SpongebotExtension.csproj
src/modules/cmdpal/Exts/TemplateExtension/TemplateExtension.csproj
src/modules/cmdpal/Exts/VirtualDesktopExtension/VirtualDesktopExtension.csproj
src/modules/cmdpal/Exts/YouTubeExtension/YouTubeExtension.csproj
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Microsoft.CmdPal.UI.ViewModels.csproj
src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/OpenUrlCommand.cs
src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ShellHelpers.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WebSearch/Commands/SearchWebCommand.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WebSearch/FallbackExecuteSearchItem.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WebSearch/Helpers/DefaultBrowserInfo.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WebSearch/NativeMethods.txt

Closes #363
The WebSearch plugin pulled in all of Wox.Infrastructure, which resulted in us pulling in _all of WPF_ as a dependency, which we obviously don't need.

get rid of dependency on Wox

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsCommandProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ActionBarViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Program.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageCommand.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageListItem.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/WinGetExtensionCommandsProvider.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/WinGetStatics.cs

This is a first best effort at #367. 
If an app is installed, we'll try to lookup if there's one and only app with that name in our big list of apps. If there is, then we'll set the command on the winget list to the "run" command. 
The uninstall command moves into the context menu, always. Even if we don't find it. This will make it harder to accidentally uninstall things. 
This also has another drive-by fix for #357. Problem wasn't just being on the UI thread, it's that we were trying to get the `.Kind` out of the activation args, after the spawning process had already died.

Attempt to correlate apps to winget packages

---

.github/actions/spell-check/expect.txt
.pipelines/v2/templates/job-build-project.yml
.pipelines/verifyAndSetLatestVCToolsVersion.ps1
.pipelines/verifyDepsJsonLibraryVersions.ps1
NOTICE.md
PowerToys.sln
README.md
src/codeAnalysis/GlobalSuppressions.cs

[WIP] Merge upstream PT #10

---

.github/actions/spell-check/expect.txt
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/IconBox.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/TypedEventHandlerExtensions.cs

I think this pilfers the `InvokeAsync` as mentioned in #333
WE can't use the actual version for the same reason we can't use that one TryEnqueue extension - the WCT MD Text block we're on uses a different version of the WCT than the latest version, so the two get confused. 
We can remove this pilfered copy after either #245 or #219
Closes #333

Pilfer `TypedEventHandlerExtensions` from WCT

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/IconCacheService.cs

Title
This is just a much simpler keybind. It harkens the mind to `alt+space`, without actually stealing that keybinding. 
I recommend `ctrl+alt+space` for the dev version (though, I'm not setting that for you)

Change the default hotkey to Win+alt+space

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ContentFormViewModel.cs
src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/FormContent.cs
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions/Microsoft.CommandPalette.Extensions.idl

Hey turns out that commented out `dataString` was important!
This isn't _terribly_ breaking, because `IFormContent` is new.

Add the form data too

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/PageViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/ListHelpers.cs

This is just a very rough prototype of "TextToSuggest", to make it do _something_. I'll link this to #358, but it's not clean enough to close it. 
I just slapped a TextBlock with the suggested text to the right of the input, just so users can see that there is a suggestion and that you can press `right` to accept it. 
The best extension to test this with is the Registry one, but that crashes heavily in `ListHelpers.InPlaceUpdateList`. I think it's for two reasons:
* a null item in the list? (we should ignore that!)
* and we're modifying the list as we're updating it (definitely shouldn't do that)
I'm guessing the second is actually the cause of #324, though I've had a hard time reproing that as of late.

Developer XAML version of TextToSuggest

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs

In #416 I tried to lock the lists before we modify them. 
Problem was, on L143 I only locked the `FilteredItems`, when `Items` can change there too. 
One singular lock for both makes the most sense anyways.

Lock both lists at the same time

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Helpers/SettingsManager.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/AllAppsSettings.cs

No one likes these settings.
The first one causes like, 1000 apps to be loaded, including everything from system32 (yikes)
The second, well, it just doesn't matter.

Disable PATH apps by default, and theWW explorer error

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandPaletteHost.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs

This static `CommandPaletteHost` instance is definitely problematic, and we should fix that. 
But for now, this fixes the issue where all extensions (including builtins) couldn't access the HWND.
We need this for #151, and it might help resolve what we were seeing in #152

Fix the HostingHwnd for built-in

---

.github/actions/spell-check/allow/names.txt
NOTICE.md
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorCommandProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.ClipboardHistory/Commands/PasteCommand.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.ClipboardHistory/Pages/ClipboardHistoryListPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/PageViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ToastViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/NativeMethods.txt
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/Settings/ExtensionPage.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml.cs
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/CopyTextCommand.cs

Well, I started by wanting to just close #385. Then I thought, "well, the copy command really needs that toast, doesn't it"
one thing lead to another, and now
Closes #385
Closes # what I never filed `ShowToast`, from https://github.com/zadjii-msft/PowerToys/pull/395

Add rudimentary support for Toast messages

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SearchQuery.cs

A fix for the issue that not all results in file search are shown when scrolling to the bottom. 
* Added a request to load new items when the user scrolls to the bottom
* Re-request items when facing an error in the file search to ensure we show all results in the list
* Search something that should get more than 20 results (I usually typed a single letter for testing)
* Scroll down to the bottom and check if new entries are loading.
Closes #351

[Search files] Loading more items fix

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/AddBookmarkForm.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/AddBookmarkPage.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarkData.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarkPlaceholderForm.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarkPlaceholderPage.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarksCommandProvider.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorCommandProvider.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/AnonymousCommand.cs
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/CommandContextItem.cs
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/CommandItem.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Bookmark/UrlCommand.cs

Re-write the bookmarks extension, to add support for edit and delete commands. This is one of the older extensions in the codebase so it was quite dated. Along the way:
* Resolved a COM threading issue with `CommandResults` (which I never saw before?)
* Also a really good idea I just had: `AnonymousCommand`s, so you can just pass a lambda to a CommandItem and that's the whole command. Don't need to define a whole command class just for that.
* Drive-by:
* Closes #251
* Closes #344

Add edit & delete to Bookmarks

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/Microsoft.CmdPal.Ext.Apps.csproj
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/AppStateModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/HistoryItem.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/RecentCommandsManager.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/AppCommand.cs

This is a very basic frecency implementation, to let MRU apps and commands show up higher in search results. 
Adds support for a `state.json` file, to store this state. Implication is the same as Terminal:
* `settings.json`: These are _your_ settings, take this with you where you go
* `state.json`: this is state _we_ own. You can take it with you at your peril. **We** control this file. 
This seemed good enough to get "VS" to match to "Visual studio" after just a single launch of VS. 
We can iterate on the weighting in the future. 
Closes #317 
This was also half-tracked in closes #147

Implement a basic recently-used-apps algorithm 

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.ClipboardHistory/Commands/CopyCommand.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsTerminal/Helpers/TerminalHelper.cs

* Allow trailing commas in terminal `settings.json`
* in the Clipboard history copy, actually use the toast message

A pair of drive-by bug fixes

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/AliasManager.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandAlias.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandItemWrapper.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/Settings/ExtensionPage.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/Settings/ExtensionPage.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs

This is a very rough UI element for setting aliases in the UI.
* the command weighting from #454 was bad. It would always grant a recent command weight. Probably shouldn't do that
* The tags could soft-crash when opening the SUI? I think that was from the ObservableCollection being created on a COM thread, then "updated" on the main thread. 
* this may be #426 but I'm not sure
Closes #92 (but it isn't pretty)

Enable editing aliases in the SUI

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/ShowWindowMessage.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/NativeMethods.txt
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/Settings/GeneralPage.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsWindow.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw

Closes #446
Setting is pretty straightforward. Same as PT Run, with an added "leave it where it is", from the Terminal codebase. 
The `DisplayArea` code is net-new (PT used WPF for that, and Terminal used C++), but it's pretty same-y to everything else. 
Drive-by fixes "holy whitespace batman", by making the SUI less wide.

Add to the SUI a setting to control where the window is summoned

---

src/modules/cmdpal/Microsoft.Terminal.UI/IconPathConverter.cpp
src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/IconInfo.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/WinGetExtensionPage.cs

Yep, it was this easy to add an SVG as an ImageSource on WinUI 3
Pretty sure it's impossible in WinUI 2 though
This is related to #182, but I think we should also like allow for `<path>` icons too

Add support for svg icons

---

src/gpo/assets/PowerToys.admx
src/gpo/assets/en-US/PowerToys.adml
src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/GpoValueChecker.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Program.cs
tools/BugReportTool/BugReportTool/ReportGPOValues.cpp

Some of the changes for GPO were already on the repo, so this PR just completes functionality.
- Completes the required .admx and .adml files for adding a policy for controlling the enabled state of CmdPal within PowerToys.
- Ports some of the GPO C++ code from the PowerToys source to C# inside CmdPal's codebase, to reduce dependencies on PowerToys.
- Check GPO during CmdPal startup in order to stop execution as soon as possible in CmdPal's lifecycle.
Note: Dashboard in Settings seems to be broken, but that doesn't seem to be caused by this specific PR.
- Copy "src\gpo\assets\PowerToys.admx" to "C:\Windows\PolicyDefinitions".
- Copy "src\gpo\assets\en-US\PowerToys.adml" to "C:\Windows\PolicyDefinitions\en-US".
- Open gpedit.msc and verify the policy exists in both Computer Configurations …

[GPO]Add a policy for controlling CmdPal enabled state

---

src/modules/AdvancedPaste/AdvancedPaste/AdvancedPaste.csproj
src/modules/EnvironmentVariables/EnvironmentVariables/EnvironmentVariables.csproj
src/modules/FileLocksmith/FileLocksmithUI/FileLocksmithUI.csproj
src/modules/Hosts/Hosts/Hosts.csproj
src/modules/MeasureTool/MeasureToolUI/MeasureToolUI.csproj
src/modules/keyboardmanager/KeyboardManagerEditorUI/KeyboardManagerEditorUI.csproj
src/modules/peek/Peek.UI/Peek.UI.csproj
src/modules/registrypreview/RegistryPreview/RegistryPreview.csproj
src/settings-ui/Settings.UI/PowerToys.Settings.csproj

Bring back the WebView2 references that were removed in https://github.com/microsoft/PowerToys/pull/37908/commits/9365bc1a7b8e386fbe0da502e83764a5e072bf7f
deps.json local check is OK

[Deps]Align Webview2 versions to fix deps.json check

---

src/settings-ui/Settings.UI/SettingsXAML/OOBE/Views/OobeShellPage.xaml.cs

Oobe changes were missing the insert of a module, causing Settings to crash when we tried to open OOBE.
Run PowerToys Settings and click "Welcome to PowerToys" and verify it doesn't crash.

[OOBE]Fix crash when opening OOBE

---

src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListItemViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/Tag.xaml.cs

* Issue the first: This hit with the media controls sample. I'm not really sure how it happened, with the menu changing which we were initializing it? But it happens, and now it doesn't
* Issues the second: `Tags` was an `ObservableCollection`, and that was getting created off the UI thread, then updated on the UI thread, and everyone was upset, and there was a pile of COM WRONG_THREAD issues. 
* ISSUE THE THIRD: FIXES THE TAG COLORS! Closes #365

A pair of threading issues: MoreCommands and Tags

---

src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Shell/Properties/Resources.Designer.cs
src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Shell/Properties/Resources.resx
src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TagViewModel.cs
src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/CommandBar.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/IndexerCommandsProvider.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Properties/Resources.Designer.cs
src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Properties/Resources.resx

* Tags have their tooltip default to their text, if no `ToolTip` is explicitly set
* add a `ctrl+k` tooltip to the more commands button
* change the naming of "indexer" to be "file search" (which is what folks really care about)
* change the naming of "shell commands" to be "Run commands" (again, this is more intuitive)

Add some tooltips, and tighten up some phrasing

---

src/common/utils/package.h
src/modules/FileLocksmith/FileLocksmithExt/PowerToysModule.cpp
src/modules/NewPlus/NewShellExtensionContextMenu/new_utilities.h
src/modules/cmdpal/CmdPalModuleInterface/dllmain.cpp
src/modules/imageresizer/dll/dllmain.cpp
src/modules/powerrename/dll/dllmain.cpp

After https://github.com/microsoft/PowerToys/commit/33ec4923898da54856336e2d8492bb737879ea39 , The logic for Command Palette module interface to verify if the package is installed is wrong because Command Palette's version doesn't track PowerToys version.
This PR makes the version check optional so we can have a different logic when checking the package for Command Palette.
Tested build from Dart and PowerToys started Command Palette correctly.

Fix CommandPalette package checking at runtime

---

src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml.cs

- Using default acrylic which is fine for notifications (it's not activated anyways because the window does not have focus..), and it removes a bunch of C# code.
- Minor tweaks to the padding of the toastwindow so it's more similar to OS toasts

ToastWindows tweak

---

src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/Storage/Win32ProgramRepository.cs

Our App plugin used the ShellLink.Open to retrieve the FullPath. But it would open the ink file exclusively. This may cause some problem. Especially when we try to upgrade some installed App through MSI installer, installer would throw exception and show a prompt to user.
Original discussion here. 
1. https://github.com/microsoft/PowerToys/pull/37654/files
2. https://[github.com/microsoft/PowerToys/pull/37924](https://github.com/microsoft/PowerToys/pull/37924)
Tested locally with VS.

Fix the MSI installer issue when App plugin is running.

---

src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml

- Tweaking the empty-screen icon + text visualization
- Fixed a bug in the details pane that clipped the content when scrolling (we were using padding on the scrollviewer vs. margin on the child grid)
- Vertically center the tags on the item line

Minor UX tweaks
