- src/modules/cmdpal/Directory.Build.props
- src/modules/cmdpal/extensions/HackerNewsExtension/HackerNewsExtension.csproj
- src/modules/cmdpal/extensions/MediaControlsExtension/MediaControlsExtension.csproj
- src/modules/cmdpal/extensions/ProcessMonitorExtension/ProcessMonitorExtension.csproj
- src/modules/cmdpal/extensions/SpongebotExtension/SpongebotExtension.csproj
- src/modules/cmdpal/extensionsdk/Microsoft.Windows.CommandPalette.Extensions.Helpers/Microsoft.CmdPal.Extensions.Helpers.csproj
- src/modules/cmdpal/src/Microsoft.CmdPal.Common/Microsoft.CmdPal.Common.csproj
- src/modules/cmdpal/src/Plugins/AllApps/AllApps.csproj
- src/modules/cmdpal/src/Plugins/Calculator/Calculator.csproj
- src/modules/cmdpal/src/WindowsCommandPalette/Microsoft.CmdPal.UI.Poc.csproj
About 750 warnings now but stuff keeps on working!
> analyzers online

- src/modules/cmdpal/.wt.json
- src/modules/cmdpal/extensions/ProcessMonitorExtension/Package.appxmanifest
- src/modules/cmdpal/src/Microsoft.CmdPal.Common/Services/LocalSettingsService.cs
- src/modules/cmdpal/src/WindowsCommandPalette/App.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainWindow.xaml
- src/modules/cmdpal/src/WindowsCommandPalette/MainWindow.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Models/ExtensionWrapper.cs
- src/modules/cmdpal/src/WindowsCommandPalette/QuitAction.cs
- src/modules/cmdpal/src/WindowsCommandPalette/SettingsActionProvider.cs
* makes `quit` not crash the app
* makes any close actually tell our extensions to exit
once again, thanks devhome folks
> Actually close extension processes when we exit

- src/modules/cmdpal/src/Plugins/AllApps/Programs/LogoType.cs
- src/modules/cmdpal/src/Plugins/AllApps/Programs/Native.cs
- src/modules/cmdpal/src/Plugins/AllApps/Programs/UWP.cs
- src/modules/cmdpal/src/Plugins/AllApps/Programs/UWPApplication.cs
> Getting apps plugin

- src/modules/cmdpal/src/WindowsCommandPalette/ActionViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/App.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/DetailsControl.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainListPage.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainPage.xaml.cs
cleanup, whitespace and brackets
> cleanup, whitespace and brackets

- src/modules/cmdpal/extensions/MediaControlsExtension/MediaActionsProvider.cs
- src/modules/cmdpal/extensions/MediaControlsExtension/MediaControlsExtension.csproj
- src/modules/cmdpal/extensions/MediaControlsExtension/MediaListItem.cs
- src/modules/cmdpal/extensions/MediaControlsExtension/PrevNextTrackAction.cs
- src/modules/cmdpal/extensions/MediaControlsExtension/TogglePlayMediaAction.cs
> media player plugin

- src/modules/cmdpal/extensions/HackerNewsExtension/HackerNewsPage.cs
- src/modules/cmdpal/src/WindowsCommandPalette/BookmarkActions.cs
- src/modules/cmdpal/src/WindowsCommandPalette/BuiltinCommands/QuitAction.cs
- src/modules/cmdpal/src/WindowsCommandPalette/BuiltinCommands/ReloadExtensionsAction.cs
- src/modules/cmdpal/src/WindowsCommandPalette/BuiltinCommands/ReloadExtensionsActionProvider.cs
- src/modules/cmdpal/src/WindowsCommandPalette/ContextItemViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/FormPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/ListPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainListItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainWindow.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MarkdownPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/PageViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Program.cs
- src/modules/cmdpal/src/WindowsCommandPalette/SettingsActionProvider.cs
- src/modules/cmdpal/src/WindowsCommandPalette/TagViewModel.cs
> Adds a 'Reload extensions' builtin ; fix a bunch of string.Empty's

- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AllAppsPage.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/LogoType.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/Native.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/PackageManagerWrapper.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/UWP.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/UWPApplication.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/Win32Program.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Microsoft.CmdPal.UI.Poc.csproj
- src/modules/cmdpal/src/WindowsCommandPalette/Views/ActionsProviderWrapper.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/MainPage.xaml.cs
getting a bunch of baseline adjustments, not totally there yet but a lot of warnings down
> lots of baseline adjustments

- src/modules/cmdpal/extensions/ProcessMonitorExtension/ProcessItem.cs
- src/modules/cmdpal/extensions/ProcessMonitorExtension/ProcessListPage.cs
- src/modules/cmdpal/extensions/ProcessMonitorExtension/ProcessMonitorActionProvider.cs
- src/modules/cmdpal/extensions/ProcessMonitorExtension/ProcessMonitorExtension.csproj
- src/modules/cmdpal/extensions/ProcessMonitorExtension/SwitchToProcess.cs
- src/modules/cmdpal/extensions/ProcessMonitorExtension/TerminateProcess.cs
parity for process termination
> refactor for process termination

- src/modules/cmdpal/README.md
- src/modules/cmdpal/extensionsdk/Microsoft.Windows.CommandPalette.Extensions/Microsoft.Windows.CommandPalette.Extensions.vcxproj
@crutkas as FYI
I'm not sure why it wasn't working for you
> Use the nuget packages at the PowerToys root 

- src/modules/cmdpal/extensions/SpongebotExtension/SpongeSettingsForm.cs
- src/modules/cmdpal/extensions/SpongebotExtension/SpongebotCommandsProvider.cs
- src/modules/cmdpal/extensions/SpongebotExtension/SpongebotSettingsPage.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/FormPage.xaml.cs
Also, add the spongebot settings page back to test
This fixes the form bubbling thing I was talking about with @crutkas
> Fix form pages

- src/modules/cmdpal/src/WindowsCommandPalette/BookmarkActions.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AppAction.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AppItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AppListItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/PackageManagerWrapper.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/Programs/Win32Program.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainListItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainWindow.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/FormPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/ListPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/MarkdownPage.xaml.cs
Fixed bookmarks so it uses proper serialization
> Bookmarks so it can serialize / deserialize via objects

- src/modules/cmdpal/WindowsCommandPalette.sln
- src/modules/cmdpal/src/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorAction.cs
- src/modules/cmdpal/src/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorActionProvider.cs
- src/modules/cmdpal/src/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorTopLevelListItem.cs
- src/modules/cmdpal/src/Exts/Microsoft.CmdPal.Ext.Calc/Microsoft.CmdPal.Ext.Calc.csproj
- src/modules/cmdpal/src/WindowsCommandPalette/Microsoft.CmdPal.UI.Poc.csproj
- src/modules/cmdpal/src/WindowsCommandPalette/Views/MainPage.xaml.cs
> moving calc back into individual project

- src/modules/cmdpal/extensions/SpongebotExtension/SpongebotSettingsPage.cs
- src/modules/cmdpal/extensionsdk/Microsoft.Windows.CommandPalette.Extensions.Helpers/Action.cs
- src/modules/cmdpal/extensionsdk/Microsoft.Windows.CommandPalette.Extensions.Helpers/Details.cs
- src/modules/cmdpal/extensionsdk/Microsoft.Windows.CommandPalette.Extensions.Helpers/MarkdownPage.cs
- src/modules/cmdpal/src/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarkPlaceholderPage.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AppAction.cs
Initial few classes for sdk refactoring
> Initial SDK refactors

- src/modules/cmdpal/extensions/MediaControlsExtension/MediaListItem.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/ListItem.cs
- src/modules/cmdpal/src/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorTopLevelListItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AppListItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainListItem.cs
Going slow and correcting stuff in as i go.
> More renaming and making stuff private

- src/modules/cmdpal/src/WindowsCommandPalette/ActionViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AppCache.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Builtins/Apps/AppListItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/ContextItemViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/FilteredListSection.cs
- src/modules/cmdpal/src/WindowsCommandPalette/ListItemViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainListItem.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainListPage.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainListSection.cs
- src/modules/cmdpal/src/WindowsCommandPalette/MainWindow.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/PageViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/RecentsListSection.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Services/ExtensionService.cs
- src/modules/cmdpal/src/WindowsCommandPalette/TagViewModel.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/ActionsProviderWrapper.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/DetailsViewModel.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/ErrorListItem.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/FormPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/FormPageViewModel.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/FormViewModel.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/ListPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/ListPageViewModel.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/MainPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/MainViewModel.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/MarkdownPage.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/MarkdownPageViewModel.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/NoOpAction.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/SectionInfoList.xaml.cs
- src/modules/cmdpal/src/WindowsCommandPalette/Views/StringNotEmptyToVisibilityConverter.xaml.cs
lotta adjusting public vs internal and getting vars setup
> Whole lotta cleanup, calling it a night

- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.vcxproj
- src/modules/cmdpal/src/Microsoft.Terminal.UI/Microsoft.Terminal.UI.vcxproj
got all but the implementation lib to work.  this then will lead into simplifying moving everything to the cmdpal root
> simplifying path roots for cpp

- src/modules/cmdpal/Exts/HackerNewsExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/Exts/MastodonExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/Exts/MastodonExtension/Properties/PublishProfiles/win-x64.pubxml
- src/modules/cmdpal/Exts/MediaControlsExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/Exts/MediaControlsExtension/Properties/PublishProfiles/win-x64.pubxml
- src/modules/cmdpal/Exts/ProcessMonitorExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/Exts/ProcessMonitorExtension/Properties/PublishProfiles/win-x64.pubxml
- src/modules/cmdpal/Exts/SpongebotExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/Exts/SpongebotExtension/Properties/PublishProfiles/win-x64.pubxml
- src/modules/cmdpal/Exts/TemplateExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/Exts/TemplateExtension/Properties/PublishProfiles/win-x64.pubxml
on move, looks like i orphaned these, mike got x64 back.  i'm getting arm now
> Recovering arm64 support and adjusting runtime ID for x64

- src/modules/cmdpal/WindowsCommandPalette/ListItemViewModel.cs
- src/modules/cmdpal/WindowsCommandPalette/Microsoft.CmdPal.UI.Poc.csproj
- src/modules/cmdpal/WindowsCommandPalette/Services/ExtensionService.cs
- src/modules/cmdpal/WindowsCommandPalette/TagViewModel.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/FormPageViewModel.xaml.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/ListPageViewModel.xaml.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/MainPage.xaml.cs
> resolving last errors

- src/modules/cmdpal/doc/command-pal-anatomy/command-palette-anatomy.md
> fixing bugs in my docs

- src/modules/cmdpal/Exts/SamplePagesExtension/Pages/SampleListPage.cs
- src/modules/cmdpal/Exts/SamplePagesExtension/Pages/SampleListPageWithDetails.cs
> small changes to sample

- src/modules/cmdpal/WindowsCommandPalette/MainWindow.xaml
- src/modules/cmdpal/WindowsCommandPalette/MainWindow.xaml.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/MainPage.xaml
- src/modules/cmdpal/WindowsCommandPalette/Views/MainPage.xaml.cs
Don't use it, don't include it.
> Remove unused title bar

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ActionBarContextItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ActionBarViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ActionBar.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ActionBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
- src/modules/cmdpal/Microsoft.CmdPal.UI/Properties/launchSettings.json
- src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml
- src/modules/cmdpal/WindowsCommandPalette/Microsoft.CmdPal.UI.Poc.csproj
With some pretend strings just to have it show up.
> Add ActionBar control

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/MainPage/MainListPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/NavigateNextCommand.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/NavigatePreviousCommand.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/NavigateToListMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Microsoft.CmdPal.UI.ViewModels.csproj
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Models/ExtensionObject`1.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/CommandProviderWrapper.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ListItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ListViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ShellViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListDetailPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListDetailPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/LoadingPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
- src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml.cs
Setup DependencyInjection for the initialization of the Built-In Providers and the main view model
Does some quick plumbing to show things in the existing UI via MVVM. 
TODO: Try loading external extensions and bring-in/abstract the extension host for the ShellViewModel
TODO: Decide if we should have ShellViewModel separate from a MainViewModel
- thinking ShellViewModel would be responsible for search functions, filtering, and delegating to the active page/functions
- MainViewModel would be associated to the 'MainPage' and handle the core functions of the built-in commands
- Do we want another entity which is aware/manages all the top-level commands.
TODO: Need to sort out how to better separate the models and viewmodels and how things behave within our special top-level 'main' page vs. …
> Setup DependencyInjection 

- src/modules/cmdpal/Exts/HackerNewsExtension/Pages/HackerNewsPage.cs
- src/modules/cmdpal/Exts/MastodonExtension/MastodonExtensionPage.cs
- src/modules/cmdpal/Exts/TemplateExtension/TemplateExtension.csproj
- src/modules/cmdpal/WindowsCommandPalette/PageViewModel.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/ListPage.xaml
- src/modules/cmdpal/WindowsCommandPalette/Views/ListPage.xaml.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/ListPageViewModel.xaml.cs
- src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/Page.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl
Just for @niels9001 to play around with.
> Add `AccentColor`s to `Page`s 

- src/modules/cmdpal/Microsoft.CmdPal.UI/Package.appxmanifest
- src/modules/cmdpal/WindowsCommandPalette/Microsoft.CmdPal.UI.Poc.csproj
- src/modules/cmdpal/WindowsCommandPalette/Package.appxmanifest
> Allow the prototype and TRA to run at the same time

- src/modules/cmdpal/check-extensions.ps1
To help debug #104, though, doesn't fix it
> Add a helper to sanity check extension installs

- src/modules/cmdpal/.wt.json
What it says on the tin. 
I usually keep this in the palette, but I keep also clean building and blowing away my `state.json`
> Add a snippet for making a new PR

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ListItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ViewModels/ListViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
- src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml.cs
This is my absolute first attempt at doing anything in the MVVM project, so I want to make sure i'm not wildly off base.
* 7afc7954b Simplest possible thing: Add the other builltins
* Just re-includes the old builtins, save for quit and reload. 
* c203c3385 Styles from the original prototype too
* Adds the ListItem styling from before, with the subtitles below. Leaves space for icons, but I'm leaving them out for now. 
* 56eb141bf Navigate deeper into lists
* My first attempt at doing things The Right Way - I think I can just send messages like this, to have the ShellPage navigate us around
* 57bb6ebe6 Navigate back too
* Similarly - if we can go in, we should be able to go out
* 5c87a62bf slide-y navigations
* I like the slide transitions, so I just wanted to see them in action again. …
> A couple small MVVM changes, as a sanity check

- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/Microsoft.CmdPal.Extensions.Helpers.csproj
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.vcxproj
- src/modules/cmdpal/extensionsdk/nuget/Microsoft.CmdPal.Extensions.SDK.nuspec
Fixing the sdk generation script after recent winmd changes.
> Fix the sdk generation script

- .pipelines/v2/templates/job-build-project.yml
These copy file tasks were from before moving sdk generation to its own stage.  These are no longer needed.
> fix pipeline build

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Shell/Commands/ExecuteItem.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Shell/ShellCommandsProvider.cs
- src/modules/cmdpal/Exts/ProcessMonitorExtension/ProcessListPage.cs
- src/modules/cmdpal/Exts/ProcessMonitorExtension/TerminateProcess.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/ListPage.xaml
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/FallbackCommandItem.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Shell/FallbackExecuteItem.cs
Rebase of #201, onto `main`, to avoid the wacky conflicts circa #200 ~ #205
Can you believe, for a second there, I almost forgot we were building a Run replacement.
> Add a fallback command for she shell command extension

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ActionBarViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/NavigateToPageMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/PageViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ActionBar.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ActionBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Styles/Button.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Views/ICurrentPageAware.cs
Has some issues still... (in part needs to update toolkit package for debounce extension update...)
_Just putting here for initial discussion._ Most of the CurrentPage clean-up should be OK.
_Filtering I've just rammed in_ for now to start testing, but there's some container duplication issues I'll have to debug Monday.
Noticing now there were some helpers in the PoC for this already, so I should have just copied from there... 😅 I'll try that Monday.
> [WIP] Some initial clean-up for Current Page and test Filtering

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
Ref #73. 
What it says on the tin. Terminate extensions when the main window closes.
> Terminate extensions on exit (again)

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/Components/ResultHelper.cs
- src/modules/cmdpal/Exts/PokedexExtension/Pages/PokedexExtensionPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TagViewModel.cs
- src/modules/cmdpal/WindowsCommandPalette/TagViewModel.cs
- src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/Tag.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl
Update the idl to allow us to specify separate FG and BG colors. I think that's better honestly.
> Two colors for tags

- src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/CommandResult.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl
> Add a very obvious GoBack command result

- src/modules/cmdpal/Exts/MastodonExtension/MastodonExtensionPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/OptionalColorToBrushConverter.cs
- src/modules/cmdpal/exts/PokedexExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/exts/PokedexExtension/Properties/PublishProfiles/win-x64.pubxml
- src/modules/cmdpal/exts/PokedexExtension/Properties/launchSettings.json
- src/modules/cmdpal/exts/VirtualDesktopExtension/Properties/PublishProfiles/win-arm64.pubxml
- src/modules/cmdpal/exts/VirtualDesktopExtension/Properties/PublishProfiles/win-x64.pubxml
- src/modules/cmdpal/exts/VirtualDesktopExtension/Properties/launchSettings.json
- src/modules/cmdpal/terminate_extensions.bat
Has a contrast issue with foreground text though:
@niels9001 think we should have a 'smart' thing that tries to create a contrasting brush for the text based on the background brush or would it be best to let devs config this as part of the tag?
For some reason my pokedex sample extension isn't loading, so that'd be the real test for colors... 😆
> Colorize the tags!

- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
> Fix TRA launching

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsPage.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/Programs/Win32Program.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
The app enumeration was very poorly stolen from PowerToys, and I clearly just skipped the most important category of thing to get right: games
happy holidays everyone
> Let mike use cmdpal to launch steam games

- src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml
- src/settings-ui/Settings.UI/ViewModels/CmdPalViewModel.cs
> Auto install msix deps packages

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
> Format will complain about trailing whitespace

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/FormControl.xaml.cs
if you don't hang onto a reference to the RenderedAdaptiveCard, then the GC might clean it up sometime, even while the card is in the UI tree. If this gets GC'd, then it'll revoke our Action handler, and the form will do seemingly nothing.
> Fix form submits, once and for all

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Indexer/Pages/IndexerPage.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SearchQuery.cs
Added pagination and updated fetching results to improve performance.
> Indexer pagination

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Indexer/Indexer/Utils/QueryStringBuilder.cs
Changed results ordering to achieve the same relevance as in the current PT Run Indexer.
> [Indexer] Results ordering

- src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsPage.xaml
> Apply xaml format to fix CI build

- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
This fixes the local build. Not sure how it slipped through while testing branding PR
@zadjii-msft FYI
> Generate msix package for local build

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
duplicate resource entry failing the build
> Fix bad merge

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
Closes #327
Pretty straightforward this. Just restore the window if we're minimized.
> Restore a minimized window, before we summon it

- src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsPage.xaml
> Xaml format

- NOTICE.md
- src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsPage.xaml.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/WinGetExtensionPage.cs
I didn't know this file existed, whoops, sorry
> Fix NOTICE and add version

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Indexer/Indexer/Utils/QueryStringBuilder.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/CSearchCatalogManager.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/CSearchCatalogManagerClass.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/CSearchManager.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/CSearchManagerClass.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/CSearchQueryHelper.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/CSearchQueryHelperClass.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/ISearchCatalogManager.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/ISearchManager.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SystemSearch/ISearchQueryHelper.cs
Changed query generation to support wildcards like PT Run.
> [Indexer] Support wildcards like PT Run

- src/modules/cmdpal/Exts/SamplePagesExtension/EvilSamplesPage.cs
Closes #221
Turns out that the crash in #221 doesn't actually repro anymore, but this sample will test that case
> Add sample to validate null arrays

- src/modules/cmdpal/WindowsCommandPalette/Services/ExtensionService.cs
- src/modules/cmdpal/WindowsCommandPalette/Views/MainPage.xaml.cs
> Fix build until POC is removed

- src/settings-ui/Settings.UI/SettingsXAML/OOBE/Views/OobeCmdPal.xaml.cs
> Fix bad merge and build

- src/modules/cmdpal/Microsoft.CmdPal.UI/CmdPal.Branding.props
> Fix icon path

- .pipelines/v2/release.yml
thanks dustin
This needed to also happen when we merged the upstream PT in #411
> BUILD: Fix signing the SDK

- src/modules/cmdpal/extensionsdk/README.md
- src/modules/cmdpal/extensionsdk/nuget/Microsoft.CommandPalette.Extensions.SDK.nuspec
> Add a license to our nuget

- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/WinGetExtensionPage.cs
> Fix the winget icon

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml
> BUILD: xaml format

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsCommandProvider.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/AllAppsSettings.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/Properties/Resources.Designer.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/Properties/Resources.resx
Expose a couple of the settings for apps as actual settings in the settings UI
> Add settings for All Apps

- src/modules/cmdpal/Exts/SamplePagesExtension/Pages/SampleSettingsPage.cs
> BUILD fix samples

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsPage.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AppListItem.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/ThumbnailHelper.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/AppCommand.cs
It fixes it On My Machine, but not on Clint's unfortunately
> Attempt to fix the crash on launch

- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
In `ListPage`, the listview had a ListViewItem inside of a ListViewItem.
> Remove nested ListViewItem

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/CommandBar.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/CommandBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Converters/KeyChordToStringConverter.cs
- Restyled the ListView to make it look like a MenuFlyout
- Added support for displaying the optional shortcut
> CommandBarFlyout restyling

- src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml.cs
Hey guess what, you need to close all the windows.
regressed in #442
> Fix a 'hang' on quit

- .pipelines/versionAndSignCheck.ps1
Boy does PT ever have a lot of sanity checking [[good]]
> Add wyhash as an exception to the version check

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandBarViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/IconInfoViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
Closes #253
This whole `item.Command.Unsafe.Name` buisiness has been weird for far too long
> Make a viewmodel for ICommand itself

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListItemViewModel.cs
This doesn't take care of #466, but it is a bug nonetheless
> This should make `ListItem.Details` observable

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
This better matches the way vscode works, even if it doesn't explicitly show the extension name in the item
Weighting might need work, but it probably _all_ needs work so 🤷
> Include the extension name in the weight of the item

- src/modules/cmdpal/Exts/SamplePagesExtension/Pages/SampleContentPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandBarViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandContextItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ContentPageViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/PerformCommandMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/UpdateCommandBarMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/CommandBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ContentPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
Basically just abstracts what we already had for list items, and uses that abstraction for contentpageviewmodel too
Closes #476
> Add support for commands on content pages

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
> Add support for alt+left to go back

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/AddBookmarkForm.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/AddBookmarkPage.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarksCommandProvider.cs
The bookmarks code was always a little wacky. This is 100% less wack.
Fixes #467
Fixes #468
> Fix bookmarks bugs by tidying code

- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml
Closes #407 (at least well enough)
Closes #466
Closes #481 
Related to #365, but doesn't fix that.
> Fix scrolling when many items (e.g. All Apps) and fix Details labels update 

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.ClipboardHistory/Helpers/ClipboardHelper.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/FallbackOpenFileItem.cs
This is stuff that regressed in #518, for the large part. 
This is also about the time I discovered #525, #526 and #527
> Fix a couple straggling breaks 

- src/modules/cmdpal/ExtensionTemplate/TemplateCmdPalExtension/Directory.Packages.props
- src/modules/cmdpal/Microsoft.Terminal.UI/Microsoft.Terminal.UI.vcxproj
- src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions/Microsoft.CommandPalette.Extensions.vcxproj
- src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions/packages.config
> Bump the remaining vcxproj's to the new WASDK version

- .github/actions/spell-check/expect.txt
- PowerToys.sln
- src/modules/MouseWithoutBorders/App/Core/Logger.cs
- src/modules/colorPicker/ColorPickerUI/App.xaml
- src/modules/colorPicker/ColorPickerUI/ColorEditorWindow.xaml
- src/modules/colorPicker/ColorPickerUI/ColorEditorWindow.xaml.cs
- src/modules/colorPicker/ColorPickerUI/ColorPickerUI.csproj
- src/modules/colorPicker/ColorPickerUI/Controls/ColorFormatControl.xaml
- src/modules/colorPicker/ColorPickerUI/Controls/ColorPickerControl.xaml
- src/modules/colorPicker/ColorPickerUI/Controls/ColorPickerControl.xaml.cs
- src/modules/colorPicker/ColorPickerUI/Helpers/AppStateHandler.cs
- src/modules/colorPicker/ColorPickerUI/MainWindow.xaml.cs
- src/modules/colorPicker/ColorPickerUI/Resources/Styles.xaml
- src/modules/colorPicker/ColorPickerUI/Views/ColorEditorView.xaml
- src/modules/colorPicker/ColorPickerUI/Views/ZoomView.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutHotkeysModel.cs
- src/modules/registrypreview/RegistryPreview.FuzzTests/FuzzTests.cs
- src/modules/registrypreview/RegistryPreview.FuzzTests/MSTestSettings.cs
- src/modules/registrypreview/RegistryPreview.FuzzTests/OneFuzzConfig.json
- src/modules/registrypreview/RegistryPreview.FuzzTests/RegistryPreview.FuzzTests.csproj
- src/modules/registrypreview/RegistryPreviewUILib/ParseHelper.cs
- src/modules/registrypreview/RegistryPreviewUILib/RegistryPreviewMainPage.Utilities.cs
Merges the upstream changes to expect.txt, which the PR is very confused about
> Merge upstream, again, again

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
Updates the description of Command Palette on the settings page
Updates the banner on the Run settings page promoting Command Palette
> Update banner on Run page and cmd pal description

- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
Usage and flow: [this one](https://github.com/zadjii-msft/PowerToys/pull/452)
> Implement the confirmation dialog

- src/modules/cmdpal/Exts/SamplePagesExtension/Pages/SampleListPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/AliasManager.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ConfirmResultViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ContentMarkdownViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/PerformCommandMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
From #536 originally
Also adds more elaborate samples for them.
Closes #399
> Add viewmodels to ConfirmResultArgs

- installer/PowerToysSetup/CmdPal.wxs
- src/modules/cmdpal/Microsoft.CmdPal.UI/CmdPal.pre.props
> [build] fix the bindir

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/RecentCommandsManager.cs
> Don't crash when there's more than 50 history items

- src/modules/cmdpal/Microsoft.CmdPal.UI/Package-Dev.appxmanifest
- src/modules/cmdpal/Microsoft.CmdPal.UI/Package.appxmanifest
- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
> Add support for a startup task

- installer/PowerToysSetup/Product.wxs
check for CIBuild instead of IsPipeline (defined for release pipeline only)
> Try fix ci

- src/modules/cmdpal/Exts/ProcessMonitorExtension/Package.appxmanifest
- src/modules/cmdpal/Exts/SamplePagesExtension/Package.appxmanifest
- src/modules/cmdpal/Microsoft.CmdPal.UI/Package-Dev.appxmanifest
- src/modules/cmdpal/Microsoft.CmdPal.UI/Package.appxmanifest
> Make sure all the MinVersion's are 19041

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Models/ExtensionWrapper.cs
The E_PATH_NOT_FOUND happens if you just delete an extension, without uninstall
This should make extension startup easier to track (at the least)
> Some better logging for extension startup

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Indexer/Pages/DirectoryExplorePage.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Indexer/Pages/IndexerPage.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/NativeMethods.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/ThumbnailHelper.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/FallbackOpenFileItem.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Pages/DirectoryPage.cs
Fixed the crash related to thumbnails.
* Set the Unicode charset for the native SHFILEINFO
* Ensure proper releasing of the icon handle
> Thumbnails fix

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsPage.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Apps/AllAppsSettings.cs
Thanks to #573 we can drop this entirely
> Get rid of the thumbnail setting
